language: node_js
node_js: lts/*
cache:
  yarn: true
  directories:
  - node_modules
env:
  global:
  - secure: NAXiDdY3rkdabUFGrgYX0NKP58x/Z258LY4G9SHfC/ZaaYqzg+A8x+x0pFEd+nzLd72oRjZ1ds6K0hwdI8biI9CAAAgUos2u38NSQkjzwsI12Z/G6nyxb9rlKMgTGoB7gRMkKRgOmAYywH1MiKFBjIxPvfh36FVT8iV3GJBd3rckWIxuI2nXO0i0B+ksAoGeok5pbkqNS9Iv5HP5FgIEzPWdA3RDCRw2uDTB13LSY7gfI03NpocFiP8cf+rkwU+et3DB0w3/perTAd1vPbKBWRnxDwrg0wgp38gF4GAUShHwcewTENGQyvuDzE/SspB7XZ7nWmZfO7JYNwAk5xLwUdjEXr6x25+Vi9+tGccEbk+6jtSKC6KZCuCbyXxx0aqpGr5ubXctrnyluLYNp9JKrKwmfR9fTmv5CwoXIeE1O+T1wqY9Nw66ZypW2VdmFhFIhL5cOmhRGCohlwz+iFvrhG/3zfyBok1w1a1+3cYHy0OSMkDaEoHbpBsGFGrOCfq65zmsZ9HRzTfj/yFeNDZSro1++yeifoyD/KKW1Qgx+hUEupJNdRrwb5BHxht5eO256WRYAApjB6lefceEr7lmgkqv3nGSApbeiw9+Z/BaY/+XXqz6sCaTF4+XlnlvuoYbf+o1GWzP6tCRwI3D/zSsaXMxo5lcGufiDobfqutUo5Q=
script:
- yarn lint
- yarn build
deploy:
  on:
    branch: master
  provider: script
  script: yarn deploy:travis -r https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  skip_cleanup: true
