language: node_js
node_js: "lts/*"
cache: yarn
script:
 - yarn lint
 - yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: yarn deploy -- -u "Travis CI <travis@travis-ci.org>" -r https://${GH_TOKEN}@github.com/danielesteban/dani.gatunes.com.git
  on:
    branch: master
